apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    type: front-end
spec:
  selector:
    matchLabels:
      type: front-end
  template:
    metadata:
      name: my-nginx
      labels:
        type: front-end
    spec:
      containers:
        - name: my-nginx-container
          image: nginx
          ports:
            - containerPort: 80
  replicas: 3